## ALFRED DATASET



In [2]:
import os, sys, platform
import os.path as osp
import json
import numpy as np
import networkx as nx
from typing import *

import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

import spacy
from spacy import displacy
import scipy.sparse as sp
import sympy; sympy.init_printing()

import torch
torch.manual_seed(42)

from IPython.core.display import display, Image, HTML
from IPython.core.debugger import set_trace



### Env Setup

In [3]:
PROJ_DIR = f"{osp.expanduser('~')}/Research/projects/embodied-ai/alf"
DATA_DIR = f"/mnt/sda4/DATA/ALFRED/data"
node = platform.node()
if (node == 'v') or ('gpu' in node):
    print("On Vector cluster")
    %env MUJOCO_GL=egl
    DATA_DIR = "/scratch/ssd004/datasets/alfred/data"
    
nb_dir = osp.split(os.getcwd())[0]
if nb_dir not in sys.path:
    sys.path.insert(0, nb_dir)

# print(f"{os.name}.{platform.system()}.{platform.release()}.{platform.node()}")
# print(f'os.cwd() -> {os.getcwd()}')

### Helpers

In [4]:
def display_matrix(m):
    display(sympy.Matrix(m))
    
def visualize(doc, dep=False):
    displacy.render(doc, style='ent', jupyter=True)
    if dep:
        displacy.render(doc, style='dep', jupyter=True, options={'distance': 70})


In [26]:
import torch
from torch import nn
from torch.nn import functional as F
from torch.nn.parameter import Parameter

in_feat = 2
out_feat = 3
m = nn.Linear(in_feat, out_feat)
inp = torch.randn(12, in_feat)
out = m(inp)
print(out.size())


torch.Size([12, 3])


In [27]:
W = Parameter(torch.Tensor(out_feat, in_feat))
b = Parameter(torch.Tensor(out_feat))

In [28]:
W.shape
# b.size()
b

Parameter containing:
tensor([2.6172e+24, 4.5644e-41, 2.6172e+24], requires_grad=True)

In [29]:
# F.linear(inp, W).shape
output = inp.matmul(W.t())
output

tensor([[-1.5839e+24,  2.4445e+33, -2.6625e-44],
        [ 5.2228e+23, -8.0608e+32,  8.4078e-45],
        [ 1.0561e+24, -1.6299e+33,  1.8217e-44],
        [-1.3657e+24,  2.1079e+33, -2.3822e-44],
        [ 2.2258e+24, -3.4354e+33,  3.7835e-44],
        [-3.6692e+24,  5.6631e+33, -6.3058e-44],
        [-5.7726e+23,  8.9094e+32, -9.8091e-45],
        [ 8.9399e+23, -1.3798e+33,  1.5414e-44],
        [ 3.7489e+24, -5.7861e+33,  6.4460e-44],
        [-2.9540e+24,  4.5591e+33, -5.0447e-44],
        [-7.3685e+23,  1.1373e+33, -1.2612e-44],
        [ 1.1122e+24, -1.7166e+33,  1.9618e-44]], grad_fn=<MmBackward>)

In [30]:
output += b
output

tensor([[ 1.0333e+24,  2.4445e+33,  2.6172e+24],
        [ 3.1394e+24, -8.0608e+32,  2.6172e+24],
        [ 3.6732e+24, -1.6299e+33,  2.6172e+24],
        [ 1.2514e+24,  2.1079e+33,  2.6172e+24],
        [ 4.8430e+24, -3.4354e+33,  2.6172e+24],
        [-1.0521e+24,  5.6631e+33,  2.6172e+24],
        [ 2.0399e+24,  8.9094e+32,  2.6172e+24],
        [ 3.5111e+24, -1.3798e+33,  2.6172e+24],
        [ 6.3661e+24, -5.7861e+33,  2.6172e+24],
        [-3.3679e+23,  4.5591e+33,  2.6172e+24],
        [ 1.8803e+24,  1.1373e+33,  2.6172e+24],
        [ 3.7294e+24, -1.7166e+33,  2.6172e+24]], grad_fn=<AddBackward0>)